/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as LocalRouteImport } from './routes/local'
import { Route as GameOverRouteImport } from './routes/game-over'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnlineWaitingRouteImport } from './routes/online.waiting'
import { Route as OnlineJoinRouteImport } from './routes/online.join'
import { Route as OnlineGameRouteImport } from './routes/online.game'
import { Route as OnlineCreateRouteImport } from './routes/online.create'
import { Route as LocalThemeRouteImport } from './routes/local.theme'
import { Route as LocalStartRouteImport } from './routes/local.start'
import { Route as LocalPairCountRouteImport } from './routes/local.pair-count'
import { Route as LocalGameRouteImport } from './routes/local.game'
import { Route as LocalCardPackRouteImport } from './routes/local.card-pack'
import { Route as LocalCardBackRouteImport } from './routes/local.card-back'
import { Route as LocalBackgroundRouteImport } from './routes/local.background'

const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const GameOverRoute = GameOverRouteImport.update({
  id: '/game-over',
  path: '/game-over',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineWaitingRoute = OnlineWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => OnlineRoute,
} as any)
const OnlineJoinRoute = OnlineJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => OnlineRoute,
} as any)
const OnlineGameRoute = OnlineGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => OnlineRoute,
} as any)
const OnlineCreateRoute = OnlineCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OnlineRoute,
} as any)
const LocalThemeRoute = LocalThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => LocalRoute,
} as any)
const LocalStartRoute = LocalStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => LocalRoute,
} as any)
const LocalPairCountRoute = LocalPairCountRouteImport.update({
  id: '/pair-count',
  path: '/pair-count',
  getParentRoute: () => LocalRoute,
} as any)
const LocalGameRoute = LocalGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => LocalRoute,
} as any)
const LocalCardPackRoute = LocalCardPackRouteImport.update({
  id: '/card-pack',
  path: '/card-pack',
  getParentRoute: () => LocalRoute,
} as any)
const LocalCardBackRoute = LocalCardBackRouteImport.update({
  id: '/card-back',
  path: '/card-back',
  getParentRoute: () => LocalRoute,
} as any)
const LocalBackgroundRoute = LocalBackgroundRouteImport.update({
  id: '/background',
  path: '/background',
  getParentRoute: () => LocalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game-over': typeof GameOverRoute
  '/local': typeof LocalRouteWithChildren
  '/online': typeof OnlineRouteWithChildren
  '/local/background': typeof LocalBackgroundRoute
  '/local/card-back': typeof LocalCardBackRoute
  '/local/card-pack': typeof LocalCardPackRoute
  '/local/game': typeof LocalGameRoute
  '/local/pair-count': typeof LocalPairCountRoute
  '/local/start': typeof LocalStartRoute
  '/local/theme': typeof LocalThemeRoute
  '/online/create': typeof OnlineCreateRoute
  '/online/game': typeof OnlineGameRoute
  '/online/join': typeof OnlineJoinRoute
  '/online/waiting': typeof OnlineWaitingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game-over': typeof GameOverRoute
  '/local': typeof LocalRouteWithChildren
  '/online': typeof OnlineRouteWithChildren
  '/local/background': typeof LocalBackgroundRoute
  '/local/card-back': typeof LocalCardBackRoute
  '/local/card-pack': typeof LocalCardPackRoute
  '/local/game': typeof LocalGameRoute
  '/local/pair-count': typeof LocalPairCountRoute
  '/local/start': typeof LocalStartRoute
  '/local/theme': typeof LocalThemeRoute
  '/online/create': typeof OnlineCreateRoute
  '/online/game': typeof OnlineGameRoute
  '/online/join': typeof OnlineJoinRoute
  '/online/waiting': typeof OnlineWaitingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game-over': typeof GameOverRoute
  '/local': typeof LocalRouteWithChildren
  '/online': typeof OnlineRouteWithChildren
  '/local/background': typeof LocalBackgroundRoute
  '/local/card-back': typeof LocalCardBackRoute
  '/local/card-pack': typeof LocalCardPackRoute
  '/local/game': typeof LocalGameRoute
  '/local/pair-count': typeof LocalPairCountRoute
  '/local/start': typeof LocalStartRoute
  '/local/theme': typeof LocalThemeRoute
  '/online/create': typeof OnlineCreateRoute
  '/online/game': typeof OnlineGameRoute
  '/online/join': typeof OnlineJoinRoute
  '/online/waiting': typeof OnlineWaitingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game-over'
    | '/local'
    | '/online'
    | '/local/background'
    | '/local/card-back'
    | '/local/card-pack'
    | '/local/game'
    | '/local/pair-count'
    | '/local/start'
    | '/local/theme'
    | '/online/create'
    | '/online/game'
    | '/online/join'
    | '/online/waiting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game-over'
    | '/local'
    | '/online'
    | '/local/background'
    | '/local/card-back'
    | '/local/card-pack'
    | '/local/game'
    | '/local/pair-count'
    | '/local/start'
    | '/local/theme'
    | '/online/create'
    | '/online/game'
    | '/online/join'
    | '/online/waiting'
  id:
    | '__root__'
    | '/'
    | '/game-over'
    | '/local'
    | '/online'
    | '/local/background'
    | '/local/card-back'
    | '/local/card-pack'
    | '/local/game'
    | '/local/pair-count'
    | '/local/start'
    | '/local/theme'
    | '/online/create'
    | '/online/game'
    | '/online/join'
    | '/online/waiting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameOverRoute: typeof GameOverRoute
  LocalRoute: typeof LocalRouteWithChildren
  OnlineRoute: typeof OnlineRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-over': {
      id: '/game-over'
      path: '/game-over'
      fullPath: '/game-over'
      preLoaderRoute: typeof GameOverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online/waiting': {
      id: '/online/waiting'
      path: '/waiting'
      fullPath: '/online/waiting'
      preLoaderRoute: typeof OnlineWaitingRouteImport
      parentRoute: typeof OnlineRoute
    }
    '/online/join': {
      id: '/online/join'
      path: '/join'
      fullPath: '/online/join'
      preLoaderRoute: typeof OnlineJoinRouteImport
      parentRoute: typeof OnlineRoute
    }
    '/online/game': {
      id: '/online/game'
      path: '/game'
      fullPath: '/online/game'
      preLoaderRoute: typeof OnlineGameRouteImport
      parentRoute: typeof OnlineRoute
    }
    '/online/create': {
      id: '/online/create'
      path: '/create'
      fullPath: '/online/create'
      preLoaderRoute: typeof OnlineCreateRouteImport
      parentRoute: typeof OnlineRoute
    }
    '/local/theme': {
      id: '/local/theme'
      path: '/theme'
      fullPath: '/local/theme'
      preLoaderRoute: typeof LocalThemeRouteImport
      parentRoute: typeof LocalRoute
    }
    '/local/start': {
      id: '/local/start'
      path: '/start'
      fullPath: '/local/start'
      preLoaderRoute: typeof LocalStartRouteImport
      parentRoute: typeof LocalRoute
    }
    '/local/pair-count': {
      id: '/local/pair-count'
      path: '/pair-count'
      fullPath: '/local/pair-count'
      preLoaderRoute: typeof LocalPairCountRouteImport
      parentRoute: typeof LocalRoute
    }
    '/local/game': {
      id: '/local/game'
      path: '/game'
      fullPath: '/local/game'
      preLoaderRoute: typeof LocalGameRouteImport
      parentRoute: typeof LocalRoute
    }
    '/local/card-pack': {
      id: '/local/card-pack'
      path: '/card-pack'
      fullPath: '/local/card-pack'
      preLoaderRoute: typeof LocalCardPackRouteImport
      parentRoute: typeof LocalRoute
    }
    '/local/card-back': {
      id: '/local/card-back'
      path: '/card-back'
      fullPath: '/local/card-back'
      preLoaderRoute: typeof LocalCardBackRouteImport
      parentRoute: typeof LocalRoute
    }
    '/local/background': {
      id: '/local/background'
      path: '/background'
      fullPath: '/local/background'
      preLoaderRoute: typeof LocalBackgroundRouteImport
      parentRoute: typeof LocalRoute
    }
  }
}

interface LocalRouteChildren {
  LocalBackgroundRoute: typeof LocalBackgroundRoute
  LocalCardBackRoute: typeof LocalCardBackRoute
  LocalCardPackRoute: typeof LocalCardPackRoute
  LocalGameRoute: typeof LocalGameRoute
  LocalPairCountRoute: typeof LocalPairCountRoute
  LocalStartRoute: typeof LocalStartRoute
  LocalThemeRoute: typeof LocalThemeRoute
}

const LocalRouteChildren: LocalRouteChildren = {
  LocalBackgroundRoute: LocalBackgroundRoute,
  LocalCardBackRoute: LocalCardBackRoute,
  LocalCardPackRoute: LocalCardPackRoute,
  LocalGameRoute: LocalGameRoute,
  LocalPairCountRoute: LocalPairCountRoute,
  LocalStartRoute: LocalStartRoute,
  LocalThemeRoute: LocalThemeRoute,
}

const LocalRouteWithChildren = LocalRoute._addFileChildren(LocalRouteChildren)

interface OnlineRouteChildren {
  OnlineCreateRoute: typeof OnlineCreateRoute
  OnlineGameRoute: typeof OnlineGameRoute
  OnlineJoinRoute: typeof OnlineJoinRoute
  OnlineWaitingRoute: typeof OnlineWaitingRoute
}

const OnlineRouteChildren: OnlineRouteChildren = {
  OnlineCreateRoute: OnlineCreateRoute,
  OnlineGameRoute: OnlineGameRoute,
  OnlineJoinRoute: OnlineJoinRoute,
  OnlineWaitingRoute: OnlineWaitingRoute,
}

const OnlineRouteWithChildren =
  OnlineRoute._addFileChildren(OnlineRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameOverRoute: GameOverRoute,
  LocalRoute: LocalRouteWithChildren,
  OnlineRoute: OnlineRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
